### ISSUE TITLE
5.5.2 release

### ISSUE THREAD

**Issue by ihusejnovic** [kamailio/kamailio-docker#13]
Hi, 

Can you please release docker image with version 5.5.2

Thanks.

**Comment by sergey-safarov** [comment]
If you want to get `kamailio/kamailio-ci:5.5.2` then it is ready.

**Comment by ihusejnovic** [comment]
Thank you Sergey, but I need image based on Debian.

**Comment by linuxmaniac** [comment]
branch is created but since docker hub is no longer building automatically unless your account is a paid one no tags are created. We need to find another way to build and publish our images.
