### ISSUE TITLE
What is relation between docker hub and GitHub?

### ISSUE THREAD

**Issue by soroshsabz** [kamailio/kamailio-docker#21]
ITNOA

As you can see in `https://github.com/kamailio/kamailio-docker/blob/master/.github/workflows/dockerhub.yml`

If I understand correctly, your docker image publish into GitHub, instead of DockerHub? and name of your repository is `kamailio/kamailio` so my question is what is `kamailio` in docker hub? is it for you? or not?

and in the end, I think it is good to publish kamailio official image to docker hub too.

thanks

**Comment by soroshsabz** [comment]
How can I get latest official docker image of kamailio? where is your official repo?

thanks

**Comment by soroshsabz** [comment]
@linuxmaniac please see my question

thanks

**Comment by sergey-safarov** [comment]
You can check this repo
https://github.com/kamailio/kamailio-docker/pkgs/container/kamailio
