### ISSUE TITLE
Where is alpine image?

### ISSUE THREAD

**Issue by soroshsabz** [kamailio/kamailio-docker#22]
ITNOA

Hi,

I could not find alpine images in https://github.com/kamailio/kamailio-docker/pkgs/container/kamailio

Where is alpine images?

thanks

**Comment by soroshsabz** [comment]
cc @linuxmaniac

**Comment by soroshsabz** [comment]
related to #21

**Comment by sergey-safarov** [comment]
Please check https://github.com/kamailio/kamailio-ci/pkgs/container/kamailio-ci


```shell
docker pull ghcr.io/kamailio/kamailio-ci:5.7.0
```

**Comment by soroshsabz** [comment]
@sergey-safarov this repo is deprecated? or not? when I use this dockers and when I use docker hub? and when I use this repo?

thanks

**Comment by sergey-safarov** [comment]
Please use GitHub repo.
Docker hub is deprecated.
