### ISSUE TITLE
Issue pulling 5.7.2-*

### ISSUE THREAD

**Issue by jmordica** [kamailio/kamailio-docker#28]
Getting a `manifest: unknown` when trying to pull any 5.7.2-* image:
```
docker pull ghcr.io/kamailio/kamailio:5.7.2-jammy
```

Any idea what's going on here? Also tried to pull by using the sha256 hash explicitly but that didn't work either.

No issues pulling previous version images.

**Comment by linuxmaniac** [comment]
I tried to remove untagged image versions from the registry and sadly I messed up. I've rebuilt them but the deb-archive.kamailio.deb has no jammy distribution so I can't do it easily.

Please use a more recent version, now you have 5.7.3 and 5.7.4 available
